# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Leo
email:
description: > # this means to ignore newlines until "baseurl:"
  Leo codesbaseurl: "" # the subpath of your site, e.g. /blog
url: "http://leosaysger.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  leosaysger
excerpt_separator: <!--more-->
paginate: 4
paginate_path: "blog/page:num"

# Build settings
markdown: kramdown
gems: [jekyll-paginate]
